### ISSUE TITLE
Adding Firebird support 

### ISSUE THREAD

**Issue by nmm** [flipm0de/NapDatabaseExport#1]
Hi, I added firebird support, if you like please let me create pull request for it. changes are: 
Implemented support for firebird database:
- included FirebirdSql.Data.FirebirdClient as nuget package
- updated target framework to 4.5.2

Fixed bug: file handle not closed when table empty
Improvement: Added quoting when CR/LF exists
Improvement: Cursor.Wait while exporting

**Comment by flipm0de** [comment]
Please create the pull request.
